[theme]
primaryColor = "#1BAE77"
backgroundColor = "#0b0d0e"
secondaryBackgroundColor = "#141a1b"
textColor = "#F2F7F3"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
